# Generated by Django 5.2.8 on 2026-03-16 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_template', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MLModel',
        ),
    ]
